### ISSUE TITLE
S3 streaming API change

### ISSUE THREAD

**Issue by Nifury** [terrycain/aioboto3#266]
* Async AWS SDK for Python version: 9.6.0
* Python version: 3.8
* Operating System: Windows/Linux

### Description

After updating to 9.6.0, the [S3 streaming download code](https://aioboto3.readthedocs.io/en/latest/usage.html#streaming-download) no longer works. 

### What I Did
```python
async with s3_ob["Body"] as stream:
    file_data = await stream.read(chunk_size)
```
throws `TypeError(): read() takes 1 positional argument but 2 were given`.

s3_ob["Body"] returns ClientResponse in aiohttp, and its read function no longer takes any argument. 
We might need to use `file_data = await stream.content.read(chunk_size)`.

**Comment by thunfischtoast** [comment]
Can confirm the problem

```
async with result["Body"] as stream:
    async for chunk, _ in stream.iter_chunks():
        ...
```

throws an error since iter_chunks() does not exist.

Python version: 3.8.10
aioboto3 version: v9.6.0

temporary fix is to fix the aioboto3 version so v9.5.0

**Comment by stan-czajka** [comment]
@Nifury 
There is an easy workaround backed by aiobotocore unit tests (check it out here: [link](https://github.com/aio-libs/aiobotocore/blob/0c6c5710e537e97b89408f62cf1d9d4f00fff5f6/tests/test_basic_s3.py#L255)). Compare `test_get_object_stream_wrapper` using chunks and no context manager and `test_get_object_stream_context` using context manager.

Digging deeper, aiohttp `ClientResponse` ([link](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L1071)) shows that probably added value from `async with` is closing the stream. `test_get_object_stream_wrapper` from aiobotocore tests also has an explicit `close()` call. 

So based on those 2 links I'd suggest the following options:
- No chunks + with:
```
async with s3_ob["Body"] as stream:
    file_data = await stream.read()
```
- Chunks + explicit close:
```
stream = s3_ob["Body"]
try:
    # probably also a loop somewhere here
    file_data = await stream.read(chunk_size)
finally:
    s3_ob["Body"].close()
```

(disclaimer: this is a simplified version, did not run that exact code snippet)

Hope that helps

**Comment by Nifury** [comment]
Thanks! It seems that s3_ob["Body"] returns `StreamingBody` which implements `read(amt)`, but its `__aenter__` function returns the underlying `ClientResponse`. 
Mystery solved!

**Comment by robmoore** [comment]
This issue has been addressed in release 10.0.0.

**Comment by Nifury** [comment]
> This issue has been addressed in release 10.0.0.

I updated to 10.0.0 but the issue still exists.

**Comment by robmoore** [comment]
Did you get an update for aiobotocore to 2.3.4 as well? In the case of the issue I was experiencing, the [fix](https://github.com/aio-libs/aiobotocore/issues/945) in aiobotocore 2.3.4 worked for me. Admittedly, the problem I ran into is not identical to yours but produced similar errors which I believed to be related. Apologies for not clarifying that assumption. 

The [change](https://github.com/aio-libs/aiobotocore/pull/946/files) utilized something similar to the possible fix you suggested when you opened the ticket.

It changes

`async for chunk, _ in self._raw_stream.iter_chunks():`

to

`async for chunk, _ in self._raw_stream.content.iter_chunks():`

**Comment by Nifury** [comment]
Yes, the aiobotocore version is 2.3.4. Unfortunately the change doesn't fix this issue. 

I don't think it's a big deal though, I was only suggesting updating the document. 😁
